FROM golang:1.22rc2-alpine3.19 as builder

RUN mkdir /app
COPY ./.env /app
COPY ./.env.dev /app
COPY ./retrieval /app
WORKDIR /app
RUN CGO_ENABLED=0 go build -mod vendor -o server ./cmd/server
RUN chmod +x /app/server

FROM alpine:3.19

RUN mkdir /app
WORKDIR /app
COPY --from=builder /app/server /app
COPY ./.env /app
COPY ./.env.dev /app
CMD /app/server 